name = "ReorderedStaticCondensation"
uuid = "f1ee79ce-6627-4fc8-8e3b-d0c930c19080"
authors = ["James Cook <james.cook@ukaea.uk>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIClusterManagers = "e7922434-ae4b-11e9-05c5-9780451d2c66"

[compat]
LinearAlgebra = "1.11.0"
MPI = "0.20.22"
MPIClusterManagers = "0.2.4"
